Criando implementação redblacktree
bcribas/benchmark-ordenacao pull request #17
Opened 2023-06-02 04:46 UTC by soaresrlucas

### Seguindo uma das tasks da issue #15, segue a implementação de uma árvore rubro negra, com algumas observações:

- Por ser uma implementação com uma estrutura diferente das demais, tentei passar os elementos do vetor para uma árvore, e, após a inserção, atualiza o vetor em ordem crescente.
- A implementação não passou no ```make testesimples```, não sei bem ao certo, mas acredito que seja devido a estrutura de árvore não ter compatibilidade com o teste automatizado.
- O código do redblacktree.c está significativamente maior que os demais algoritmos. Não sei se está como esperado.

Criei esse Pull Request mais para receber um feedback de como adequar o código ao repositório, fiz uma série de testes sem usar o makefile e está tudo correto.
Desde já agradeço.

2023-06-03 01:55 UTC, bcribas requested changes
Está no caminho, apenas pequenas correções são necessárias. []

2023-06-03 01:55 UTC, bcribas commented on redblacktree.c
> +int idx = 0;
esta variável global não é inicializada corretamente. Não é sempre que o vetor a ser ordenado inicia em 0, ele inicia sempre em `l`, remover esta variável global e usar o indice como argumento na função em-ordem

2023-06-03 01:55 UTC, bcribas commented on redblacktree.c
> +    for(int i = l; i < r; i++) {
O intervalo de ordenação é fechado, `[l,r]` , logo `r` faz parte do vetor, a condição deve ser `i<=r`

2023-06-03 01:55 UTC, bcribas commented on redblacktree.c
> +	if(r == NULL)
atenção na indentação. Parte do código está indentado com tab e outra parte com espaços. Prefira indentação com 2 espaços (tal como está o arquivo .h)

2023-06-03 01:55 UTC, bcribas commented on redblacktree.c
> +		v[idx] = r->item;
este `idx` pode acessar índice errado no vetor. A melhor estratégica é passar para a função o endereço de memória da próxima posição vaga do vetor.

Logo `idx` pode ser uma variável local sempre com valor `0`

2023-06-03 01:55 UTC, bcribas commented on redblacktree.c
> +	em_ordem(r->dir, v);
e aqui seria `em_ordem(r->dir,&v[idx])`

2023-06-03 01:55 UTC, bcribas commented on redblacktree.h
> +#endif
adicionar last EOL

2023-06-03 01:56 UTC, bcribas commented on redblacktree.c
> +    for(int i = l; i < r; i++) {
isso aqui é um dos motivos de não ter passado no testesimples! Faltou elemento no vetor gerado :)

2023-06-04 16:26 UTC, soaresrlucas commented on redblacktree.c
> +		v[idx] = r->item;
Não entendi essa parte. A função ```em_ordem``` receberia como parâmetro a próxima posição do vetor? Eu poderia possar como sendo ```l``` e ao passar cada item da árvore para o vetor eu passo como ```v[l++] = r->item```? Aí em caso de itens repetidos ele coloca repetido no vetor baseado no ```item->repeticoes```.

2023-06-04 16:27 UTC, soaresrlucas commented on redblacktree.h
> +#endif
O que seria last EOL? Estava seguindo as outras .h do repositório, apenas mudando para ```redblacktree```

2023-06-06 03:57 UTC, bcribas commented on redblacktree.c
> +		v[idx] = r->item;
como esta função é recursiva, você deveria manter, via parâmetro, onde está a posição vazia mais à esquerda. Mas para evitar isso você pode usar um "joguinho" de ponteiros, passando sempre a referência da posição que está livre, assim toda instância da função vai ver como v[0].

2023-06-06 03:59 UTC, bcribas commented on redblacktree.h
> +#endif
last EOL é o último fim de linha. Ou seja a última linha (a linha 23) está sem um `\n`. Se isso aconteceu em outros arquivos é bom verificar.

2023-06-06 18:45 UTC, closed without merging