Criando implementação redblacktree
bcribas/benchmark-ordenacao pull request #18
Opened 2023-06-06 18:54 UTC by soaresrlucas

### Realizei as alterações solicitadas no último pull request e realizei testes manuais e aparentemente o ```em_ordem``` acessa o índice correto e modifica o vetor como deveria ser, mas o ```make testesimples``` ainda da erro.

Não sei o que estou fazendo de errado, se puder me dar um luz eu agradeceria.

2023-06-07 12:53 UTC, bcribas requested changes
bem melhor!

2023-06-07 12:53 UTC, bcribas commented on redblacktree.c
> +}
a função não fez o return de `t`. Assim os elementos nunca são inseridos. Em alguns casos gera segfault

2023-06-07 12:53 UTC, bcribas commented on redblacktree.c
> +void redblacktree(Item *v, int l, int r){
gostaria que a função fosse chamada `redblacktreesort`, pois é uma função de ordenação. Aí precisa atualizar os nomes dos arquivos para `redblacktreesort.c`, `redblacktreesort.h`, atualizar o nome no protótipo no `redblacktreesort.h`, na `main.h` e no `Makefile`

2023-06-07 12:53 UTC, bcribas commented on redblacktree.c
> +}
seria adequado que ao final desta função os nós da redblack fossem liberados da memória. Os elementos podem ser removidos adicionando abaixo da linha 87 um `free(r)`. Aí a função `em_ordem` seria já destrutiva.

2023-06-07 12:53 UTC, bcribas commented on redblacktree.c
> +no* novo_no(Item item, color color) {
todas as funções que não estão no .h defina como `static` , assim demonstra que são funções que devem ser utilizadas somente no próprio arquivo.

2023-06-07 22:00 UTC, soaresrlucas commented on redblacktree.c
> +void redblacktree(Item *v, int l, int r){
Sem problemas

2023-06-10 02:38 UTC, bcribas commented on redblacktreesort.h
> +static no* novo_no(Item item, color color);
Essas funções não devem aparecer no .h. No .h deve haver somente as funções que outros pedaços do programa podem usar, neste caso é somente o redblacktreesort.

No .c que essas funções devem ter o static na frente.

2023-06-15 01:20 UTC, merged