bubblesortsentinela adicionado
bcribas/benchmark-ordenacao pull request #8
Opened 2021-07-26 17:23 UTC by chfleury

Adicionando bubble sort com uma sentinela, para que o algoritmo aproveite o estado quase ordenado do vetor, caso a sentinela perceba que não foi feita nenhuma troca em um determinado loop, significa que o vetor já está ordenado, finalizando assim a ordenação.

2021-07-29 15:29 UTC, bcribas requested changes
Para aprovar peço pequenas modificações para deixar a implementação compatível com os outros algoritmos.

2021-07-29 15:29 UTC, bcribas commented on bubblesortsentinela.c
> +void swap(int *x, int *y) {
utilize as macros que estão definidas no arquivo `ordenacaomacros.h`

2021-07-29 15:29 UTC, bcribas commented on bubblesortsentinela.c
> +void bubbleSort(int A[], int n) {
As funções de ordenação devem receber um vetor do tipo `Item`, o `l` e `r`

2021-07-29 15:29 UTC, bcribas commented on bubblesortsentinela.c
> +}
faltou o fim de linha

2021-07-29 15:29 UTC, bcribas commented on bubblesortsentinela.c
> +int main () {
os algoritmos entram sem a função `main`

2021-07-29 15:29 UTC, bcribas commented on bubblesortsentinela.c
> +      if (A[j] > A[j+1]){
as comparações devem ser feitas com as macros definidas em `ordenacaomacros.h`

2021-07-29 15:29 UTC, bcribas commented on bubblesortsentinela.c
> +  for (int i = 0; i<n-1; i++) {
O vetor deve começar em `l` e terminar em `r`, assim podemos ordenar somente um pedaço do vetor (pode parecer não ter sentido em um algoritmo elementar, mas deixa o acesso às funções mais adequado).

2021-07-30 13:15 UTC, bcribas requested changes
de maneira cosmética:
 - Nome da função deixar o S do `sort` em minúsculo `bubblesortSentinela`
 - Remover as linhas vazias 10 e 15
 - remover as chaves das linhas 21 e 23 (as chaves são opcionais e sem elas o código fica mais limpo).
 
Aproveitando que você já está bem avançado poderia  criar o `bubblesortsentinela.h`, copiando o arquivo `bubblesort.h` e atualizando o nome da função para `bubblesortSentinela`

Também adicionar as entradas para o bubblesortSentinela no arquivo `main.h`, basta replicar o `elif` de outra versão.

Com isso fecharia um commit ótimo!

2021-07-30 19:33 UTC, chfleury commented
> de maneira cosmética:
> 
> * Nome da função deixar o S do `sort` em minúsculo `bubblesortSentinela`
> * Remover as linhas vazias 10 e 15
> * remover as chaves das linhas 21 e 23 (as chaves são opcionais e sem elas o código fica mais limpo).
> 
> Aproveitando que você já está bem avançado poderia criar o `bubblesortsentinela.h`, copiando o arquivo `bubblesort.h` e atualizando o nome da função para `bubblesortSentinela`
> 
> Também adicionar as entradas para o bubblesortSentinela no arquivo `main.h`, basta replicar o `elif` de outra versão.
> 
> Com isso fecharia um commit ótimo!

Acho que agora foi kkk, eu nunca tinha mexido com esses arquivos .h antes

2021-07-30 19:56 UTC, bcribas requested changes
correções

2021-07-30 19:56 UTC, bcribas commented on bubblesortsentinela.c
> + * Copyright(C) 2020, Bruno César Ribas <bruno.ribas@unb.br>
Deixa o seu nome aqui :)

2021-07-30 19:56 UTC, bcribas commented on bubblesortsentinela.h
> + * Copyright(C) 2020, Bruno César Ribas <bruno.ribas@unb.br>
esse arquivo também foi criado por você

2021-07-30 19:56 UTC, bcribas commented on main.h
> +#elif defined(__bubblesortSentinela__)
esse defined precisa bater com o nome do arquivo. Já que o arquivo ficou tudo minúsculo, precisa ser `__bubblesortsentinela__`.

2021-07-30 20:04 UTC, bcribas commented on bubblesort.h
> + * Copyright(C) 2020, Christian Fleury <chfleurysiq@gmail.com>
Modificação foi feita no arquivo errado. Deveria ser no `bubblesortsentinela.h`

2021-07-30 20:05 UTC, bcribas requested changes
Houve uma modificação em um arquivo errado

2021-07-30 20:05 UTC, bcribas commented on bubblesortsentinela.h
> + * Copyright(C) 2020, Bruno César Ribas <bruno.ribas@unb.br>
A modificação foi no arquivo errado

2021-07-30 20:12 UTC, bcribas requested changes

2021-07-30 20:12 UTC, bcribas commented on bubblesort.h
> +#endif
simiu um fim de linha do arquivo que não deveria ser modificado no seu PR. Tire esse arquivo totalmente do PR

2021-07-30 20:17 UTC, chfleury commented on bubblesort.h
> +#endif
prontinho, é que meu editor automaticamnte formata o arquivo ao salvar, desculpe pela bagunça, é meu primeiro PR

2021-07-30 20:25 UTC, bcribas requested changes
O arquivo `bubblesort.h` sumiu do repositório pois foi feito um `git mv bubblesort.h bubblesortsentinela.h`. O arquivo `bubblesort.h` deve ficar intocado.

2021-07-30 20:57 UTC, closed without merging