adicionando o RadixSort
bcribas/benchmark-ordenacao pull request #9
Opened 2021-07-27 20:26 UTC by ErickMVdO

Fiz algumas mudanças para encaixar nos parâmetros passados na main, mas ta tudo funcionando.

2021-07-29 15:25 UTC, bcribas requested changes
O commit está bom e apenas 3 pequenas coisas precisam ser ajustadas

2021-07-29 15:25 UTC, bcribas commented on Makefile
> +radixsort: main.c radixsort.c separa.c insertionsort.c mergesort.c
O `radixsort` realmente depende do `separa`, `insertionsort` e `mergesort`?

2021-07-29 15:25 UTC, bcribas commented on radixsort.c
> +}
faltou o fim de linha

2021-07-29 15:25 UTC, bcribas commented on radixsort.h
> +#endif
faltou o fim de linha

2021-07-29 18:28 UTC, ErickMVdO commented on Makefile
> +radixsort: main.c radixsort.c separa.c insertionsort.c mergesort.c
Realmente, eu pensei que eles seriam rodados juntos só para comparar mesmo.

2021-07-29 18:30 UTC, ErickMVdO commented
Problemas resolvidos!

2021-07-29 19:47 UTC, bcribas requested changes
Algumas modificações didáticas para a implementação

2021-07-29 19:47 UTC, bcribas commented on radixsort.c
> +    int *zero = malloc(n * sizeof(int));
nesta implementação o `n` equivale ao valor de `r`  e, portanto, não representa o tamanho do vetor sendo ordenado (pode ser super-estimado), há dois caminhos para resolver isso:
1. Adaptar neste ponto o tamanho de cada vetor para o cálculo correto `(n-l+1)`, ou;
2. trocar o parâmetro do vetor de `n` para `r` e declarar uma variável `n` com o tamanho do vetor logo no início da função, e atualizar todos os usos de `n` na função

2021-07-29 19:47 UTC, bcribas commented on radixsort.c
> +  free(zero);
essa cadeia de `free` parecem estar desalinhados na indentação

2021-07-29 21:42 UTC, ErickMVdO commented
Corrigido!

2021-07-29 22:18 UTC, bcribas commented
Para um arquivo com 1024 elementos ordenados de maneira reversa:
```Bash
$ ./radixsort < input/10-reverso 
double free or corruption (out)
Aborted
```

Log do valgrind:
```
==133574== Conditional jump or move depends on uninitialised value(s)
==133574==    at 0x109A25: radixsort (radixsort.c:113)
==133574==    by 0x109203: main (main.c:28)
==133574== 
==133574== Conditional jump or move depends on uninitialised value(s)
==133574==    at 0x109A86: radixsort (radixsort.c:117)
==133574==    by 0x109203: main (main.c:28)
==133574== 
==133574== Conditional jump or move depends on uninitialised value(s)
==133574==    at 0x109AE7: radixsort (radixsort.c:121)
==133574==    by 0x109203: main (main.c:28)
==133574== 
==133574== Conditional jump or move depends on uninitialised value(s)
==133574==    at 0x109B48: radixsort (radixsort.c:125)
==133574==    by 0x109203: main (main.c:28)
==133574== 
==133574== Conditional jump or move depends on uninitialised value(s)
==133574==    at 0x109BA9: radixsort (radixsort.c:129)
==133574==    by 0x109203: main (main.c:28)
==133574== 
==133574== Conditional jump or move depends on uninitialised value(s)
==133574==    at 0x109C0A: radixsort (radixsort.c:133)
==133574==    by 0x109203: main (main.c:28)
==133574== 
==133574== Conditional jump or move depends on uninitialised value(s)
==133574==    at 0x109C6B: radixsort (radixsort.c:137)
==133574==    by 0x109203: main (main.c:28)
==133574== 
==133574== Conditional jump or move depends on uninitialised value(s)
==133574==    at 0x109CCC: radixsort (radixsort.c:141)
==133574==    by 0x109203: main (main.c:28)
==133574== 
==133574== Conditional jump or move depends on uninitialised value(s)
==133574==    at 0x109D2D: radixsort (radixsort.c:145)
==133574==    by 0x109203: main (main.c:28)
==133574== 
==133574== Conditional jump or move depends on uninitialised value(s)
==133574==    at 0x109D8E: radixsort (radixsort.c:149)
==133574==    by 0x109203: main (main.c:28)
==133574== 
```

Agora vou deixar você descobrir ;)

Outra coisa importante é que o `sizeof` dos `malloc`s devem ser de `Item` e não de `int`, para garantir que sempre vai fazer o `malloc` certo, por exemplo caso o `Item` seja um `long`.

2021-07-29 23:16 UTC, ErickMVdO commented
Fiz alguns testes aqui, e para os valores acima de 1000 ordenado ou 1018 ordenado de forma reversa o código realmente está quebrando. Porém, quando eu tiro a sequência de `free` isso para de acontecer. Sabe o por quê?

2021-07-30 13:06 UTC, bcribas commented
> Fiz alguns testes aqui, e para os valores acima de 1000 ordenado ou 1018 ordenado de forma reversa o código realmente está quebrando. Porém, quando eu tiro a sequência de `free` isso para de acontecer. Sabe o por quê?

A dica está no log do valgrind, os seus laços nas linhas 113 até 149 dependem de valores não inicializados. Lembre que o `malloc` não inicializa o vetor, então é incerto o que tem lá dentro. E no caso pode acontecer de algum dos vetores não possuir `0` e aí você está corrompendo estruturas que armazenam informações de malloc (por isso o problema fica evidente com o `free`). Além disso o vetor vai precisar ser 1 elemento maior que `(n-l+1)` para garantir que vai ter um `0` no fim do vetor, senão os seus laços podem não parar em um vetor `v` que possua todos os elementos repetidos.

A implementação da parte de "reagrupamento" dos vetores dividos possui como premissa algo que não é correto, e em geral usamos '\0' para representar um char de valor 0, os vetores são do tipo `Item`, a comparação deveria ser com `0`. 

Arrumando a comparação, explicada acima, você precisa resolver o problema do vetor não inicializado, isso pode ser resolvido se trocar o `malloc` por `calloc`, mas isso pode ser bem lento, pois o `calloc` vai fazer algo parecido com um `memset` no vetor (que essencialmente percorre o vetor inicializando), e com 10 vetores (potencialmente grandes) a penalidade pode ser grande.

Acho que seria mais rápido se você (nas linhas 56 a 105) depois de armazenar o valor já poderia salvar um `0` ao lado, mas isso envolve crescer o tamanho do vetor em 1 posição, pois imagina um vetor que só tenha `1`.

2021-07-30 14:03 UTC, ErickMVdO commented
Eu não sabia dessa informação do malloc, mas corrigi o erro seguindo suas dicas

2021-07-30 19:46 UTC, bcribas requested changes
correções

2021-07-30 19:46 UTC, bcribas commented on radixsort.c
> +  // n = quantidade de números no vetor
neste caso o `n` representa o índice mais a direita do vetor e não, necessariamente, o tamanho.

2021-07-30 19:46 UTC, bcribas commented on radixsort.c
> +        zero[z] = v[i];
adicionar a linha
`zero[z+1]=0`

2021-07-30 19:46 UTC, bcribas commented on radixsort.c
> +        um[u] = v[i];
adicionar a linha
`um[u+1]=0`

E para todos os outros vetores, até o `nove`

2021-07-30 19:49 UTC, bcribas commented
> Eu não sabia dessa informação do malloc, mas corrigi o erro seguindo suas dicas

Faltou uma correção para ter a inicialização do vetor corretamente. Do jeito que o código está pode ser que ele falhe quando for chamado diversas vezes em um código, por conta da não inserção de `0` no final dos vetores.

O efeito é parecido com a do código abaixo:
```
#include <stdio.h>
#include <stdlib.h>
int main(void)
{
  int *a=malloc(4*sizeof(int));
  for(int i=0;i<4;i++)
  {
    a[i]=3+i;
    printf("%d\n",i);
  }
  free(a);
  a=malloc(4*sizeof(int));
  for(int i=0;i<4;i++)
    printf("%d\n",i);
}
```
Veja que mesmo fazendo o `free` e alocando novamente o vetor os valores permanecem inalterados. Essa é a característica do `malloc` de nào inicializar a região de memória recém-alocada. Em geral funciona nos programas por causa de alguma configuração no Kernel que garante que toda memória alocada pela primeira vez estará zerada (isso é para garantir que um processo não consiga recuperar dados de outros programas).

2021-07-30 21:32 UTC, ErickMVdO commented on radixsort.c
> +        dois[d] = 0;
Tem alguma diferença adicionar o 0 no final dos vetores dessa maneira ou colocando o `zero[z+1]=0` em cada um dos `if`s equivalentes?

2021-07-30 22:21 UTC, bcribas commented on radixsort.c
> +        dois[d] = 0;
Passou batido essa parte. Então o que precisa fazer é deixar isso logo após o laço, assim eliminamos a necessidade do `if`

2021-07-30 22:29 UTC, ErickMVdO commented on radixsort.c
> +        dois[d] = 0;
Feito.

2021-07-30 22:54 UTC, merged